VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= Developer ID Application
EXPECTED_CODESIGN_AUTHORITY_PREFIX ?= Authority=Developer ID Application:
DEVELOPMENT_TEAM ?=
CODESIGN_STYLE ?= Manual
NOTARIZE ?= 0
NOTARYTOOL_PROFILE ?= winmux
NOTARYTOOL_KEYCHAIN ?=
GENERATE_APPCAST ?= 0
RELEASE_REPOSITORY ?= alanzchen/winmux
UPDATE_FEED_URL ?= https://raw.githubusercontent.com/$(RELEASE_REPOSITORY)/updates/prerelease.xml
RELEASE_DIR ?= .release
RELEASE_DERIVED_DATA_DIR ?= $(CURDIR)/.local/release-cache/arm64
RELEASE_TAG ?= v$(VERSION)
RELEASE_NOTES ?= auto
PUBLISH ?= 0
APP_INSTALL_DIR ?= /Applications
CLI_STAGE_PATH ?= $(RELEASE_DIR)/winmux
LOCAL_INSTALL_ROOT ?= $(CURDIR)/.local/install
INSTALL_LOCK_HELD ?= 0
LAUNCH_AFTER_INSTALL ?= 1
SPARKLE_PUBLIC_KEY ?= /BxxDxDj+dLkdpsMkrnM112D+uUItM3FVE8cDe/7f7c=
SPARKLE_ACCOUNT ?= winmux-alanzchen
SPARKLE_PRIVATE_KEY_FILE ?=
ARGS ?=

export VERSION CODESIGN_IDENTITY EXPECTED_CODESIGN_AUTHORITY_PREFIX DEVELOPMENT_TEAM CODESIGN_STYLE
export NOTARIZE NOTARYTOOL_PROFILE NOTARYTOOL_KEYCHAIN GENERATE_APPCAST RELEASE_REPOSITORY
export RELEASE_DIR RELEASE_TAG RELEASE_NOTES PUBLISH CLI_STAGE_PATH UPDATE_FEED_URL
export RELEASE_DERIVED_DATA_DIR
export SPARKLE_PUBLIC_KEY SPARKLE_ACCOUNT SPARKLE_PRIVATE_KEY_FILE

.PHONY: generate xcodeproj build build-clean run run-clean cli cli-release release install install-staged verify-installed installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_STYLE="$(CODESIGN_STYLE)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	export XCODEGEN_WINMUX_UPDATE_FEED_URL="$(UPDATE_FEED_URL)" && \
	export XCODEGEN_WINMUX_SPARKLE_PUBLIC_KEY="$(SPARKLE_PUBLIC_KEY)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build --arch arm64 && \
	swift build --arch arm64 --target AppBundleTests && \
	debug_build_dir="$$(swift build --arch arm64 --show-bin-path | /usr/bin/tail -n 1)" && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r "$$debug_build_dir/winmux" .debug && \
	cp -r "$$debug_build_dir/WinMuxApp" .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

cli-release:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	swift build -c release --arch arm64 --build-system native --product winmux -Xswiftc -warnings-as-errors && \
	cli_build_dir="$$(swift build -c release --arch arm64 --build-system native --show-bin-path | /usr/bin/tail -n 1)" && \
	cli_stage_path="$(CLI_STAGE_PATH)" && \
	test -x "$$cli_build_dir/winmux" && \
	mkdir -p "$$(dirname "$$cli_stage_path")" && \
	/usr/bin/install -m 755 "$$cli_build_dir/winmux" "$$cli_stage_path" && \
	if [ "$(CODESIGN_IDENTITY)" = "-" ]; then \
	    /usr/bin/codesign --force --sign - "$$cli_stage_path"; \
	else \
	    /usr/bin/codesign --force --options runtime --timestamp --sign "$(CODESIGN_IDENTITY)" "$$cli_stage_path"; \
	fi && \
	/usr/bin/codesign --verify --strict --verbose=2 "$$cli_stage_path" && \
	archs="$$(/usr/bin/lipo -archs "$$cli_stage_path")" && \
	if [ "$$archs" != arm64 ]; then echo "CLI must contain only arm64; found $$archs" >&2; exit 1; fi && \
	sdk="$$(/usr/bin/vtool -show-build-version "$$cli_stage_path" | /usr/bin/sed -nE "s/^ *sdk ([0-9.]+).*/\1/p" | /usr/bin/head -n 1)" && \
	expected_sdk="$$(/usr/bin/xcrun --show-sdk-version)" && \
	if [ "$$sdk" != "$$expected_sdk" ]; then echo "CLI must record the macOS $$expected_sdk SDK it was built with; found $$sdk" >&2; exit 1; fi'

release:
	/bin/bash script/build-release.sh --check
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	$(MAKE) cli-release VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" CLI_STAGE_PATH="$(CLI_STAGE_PATH)"
	/bin/bash script/build-release.sh

.PHONY: prerelease-local
prerelease-local:
	python3 -B script/local-prerelease.py

# Unattended previews: `ship` returns once the release runs in the dedicated release worktree;
# `ship-wait` blocks until it ends and prints a short summary (exit 0 = published).
.PHONY: ship ship-check ship-wait ship-status
ship:
	python3 -B script/ship.py start $(if $(COMMIT),--commit "$(COMMIT)")

ship-check:
	python3 -B script/ship.py start --dry-run $(if $(COMMIT),--commit "$(COMMIT)")

ship-wait:
	python3 -B script/ship.py wait $(if $(RUN),"$(RUN)") $(if $(TIMEOUT),--timeout "$(TIMEOUT)")

ship-status:
	python3 -B script/ship.py status $(if $(RUN),"$(RUN)")

install:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	local_install_root="$(LOCAL_INSTALL_ROOT)"; \
	mkdir -p "$$local_install_root"; \
	local_install_root="$$(cd "$$local_install_root" && pwd -P)"; \
	install_lock="$$local_install_root/.install.lock"; \
	if ! mkdir "$$install_lock" 2>/dev/null; then \
	    echo "Another WinMux build or install is already in progress: $$install_lock" >&2; \
	    exit 1; \
	fi; \
	cleanup_install_lock() { rmdir "$$install_lock" >/dev/null 2>&1 || true; }; \
	trap cleanup_install_lock EXIT; \
	$(MAKE) release VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" GENERATE_APPCAST=0 PUBLISH=0; \
	$(MAKE) install-staged VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" CLI_STAGE_PATH="$(CLI_STAGE_PATH)" LOCAL_INSTALL_ROOT="$$local_install_root" APP_INSTALL_DIR="$(APP_INSTALL_DIR)" INSTALL_LOCK_HELD=1 LAUNCH_AFTER_INSTALL="$(LAUNCH_AFTER_INSTALL)"'

install-staged:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	app_path="$$release_dir/$$app_name-$(VERSION).xcarchive/Products/Applications/$$app_name.app"; \
	cli_path="$(CLI_STAGE_PATH)"; \
	dist_zip_path="$$release_dir/$$app_name-$(VERSION)-macOS.zip"; \
	local_install_root="$(LOCAL_INSTALL_ROOT)"; \
	install_dir="$(APP_INSTALL_DIR)"; \
	mkdir -p "$$local_install_root" "$$install_dir"; \
	local_install_root="$$(cd "$$local_install_root" && pwd -P)"; \
	install_dir="$$(cd "$$install_dir" && pwd -P)"; \
	install_path="$$install_dir/$$app_name.app"; \
	test -d "$$app_path"; \
	test -x "$$cli_path"; \
	test -f "$$dist_zip_path"; \
	dist_hash="$$(/usr/bin/shasum -a 256 "$$dist_zip_path" | /usr/bin/awk '\''{print $$1}'\'')"; \
	install_target_hash="$$(printf "%s" "$$install_path" | /usr/bin/shasum -a 256 | /usr/bin/awk '\''{print $$1}'\'')"; \
	release_id="$(VERSION)-$$dist_hash-$$install_target_hash"; \
	releases_dir="$$local_install_root/releases"; \
	pair_path="$$releases_dir/$$release_id"; \
	mkdir -p "$$releases_dir"; \
	if [ "$(INSTALL_LOCK_HELD)" != "1" ]; then \
	    install_lock="$$local_install_root/.install.lock"; \
	    if ! mkdir "$$install_lock" 2>/dev/null; then \
	        echo "Another WinMux install is already in progress: $$install_lock" >&2; \
	        exit 1; \
	    fi; \
	    cleanup_install_lock() { rmdir "$$install_lock" >/dev/null 2>&1 || true; }; \
	    trap cleanup_install_lock EXIT; \
	fi; \
	if [ ! -d "$$pair_path" ]; then \
	    staging_path="$$(/usr/bin/mktemp -d "$$local_install_root/.staging.XXXXXX")"; \
	    mkdir -p "$$staging_path/bin"; \
	    ditto "$$app_path" "$$staging_path/$$app_name.app"; \
	    /usr/bin/install -m 755 script/winmux-launcher.sh "$$staging_path/bin/winmux"; \
	    printf "%s\n" "$$install_path" > "$$staging_path/bin/winmux-app-path"; \
	    mv "$$staging_path" "$$pair_path"; \
	fi; \
	test -d "$$pair_path/$$app_name.app"; \
	test -x "$$pair_path/bin/winmux"; \
	python3 -B script/verify-bundle-executables.py "$$pair_path/$$app_name.app"; \
	codesign --verify --deep --strict --verbose=2 "$$pair_path/$$app_name.app"; \
	codesign --verify --strict --verbose=2 "$$pair_path/$$app_name.app/Contents/Helpers/winmux"; \
	cmp -s "$$pair_path/$$app_name.app/Contents/MacOS/$$app_name" "$$app_path/Contents/MacOS/$$app_name"; \
	cmp -s "$$pair_path/$$app_name.app/Contents/Helpers/winmux" "$$cli_path"; \
	cmp -s "$$pair_path/bin/winmux" script/winmux-launcher.sh; \
	test "$$(cat "$$pair_path/bin/winmux-app-path")" = "$$install_path"; \
	for executable in "$$pair_path/$$app_name.app/Contents/MacOS/$$app_name" "$$pair_path/$$app_name.app/Contents/Helpers/winmux"; do \
	    archs="$$(/usr/bin/lipo -archs "$$executable")"; \
	    if [ "$$archs" != arm64 ]; then echo "$$executable must contain only arm64; found $$archs" >&2; exit 1; fi; \
	done; \
	mkdir -p "$$install_dir"; \
	current_path="$$local_install_root/current"; \
	if [ -e "$$current_path" ] && [ ! -L "$$current_path" ]; then \
	    echo "Refusing to replace non-symlink: $$current_path" >&2; \
	    exit 1; \
	fi; \
	old_current="$$(readlink "$$current_path" 2>/dev/null || true)"; \
	next_path="$$install_dir/.$$app_name.app.next.$$$$"; \
	backup_path="$$install_dir/.$$app_name.app.rollback.$$(date +%Y%m%d%H%M%S).$$$$"; \
	current_next="$$local_install_root/.current.$$$$"; \
	rm -rf "$$next_path"; \
	ditto "$$pair_path/$$app_name.app" "$$next_path"; \
	codesign --verify --deep --strict --verbose=2 "$$next_path"; \
	was_running=0; \
	if pgrep -x "$$app_name" >/dev/null 2>&1; then \
	    was_running=1; \
	    if [ "$(LAUNCH_AFTER_INSTALL)" = "1" ]; then \
	        osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	    else \
	        pkill -TERM -x "$$app_name" >/dev/null 2>&1 || true; \
	    fi; \
	fi; \
	for attempt in $$(seq 1 100); do \
	    if ! pgrep -x "$$app_name" >/dev/null 2>&1; then break; fi; \
	    sleep 0.1; \
	done; \
	if pgrep -x "$$app_name" >/dev/null 2>&1; then \
	    echo "WinMux did not quit; leaving the installed app untouched" >&2; \
	    rm -rf "$$next_path"; \
	    exit 1; \
	fi; \
	had_previous=0; \
	if [ -e "$$install_path" ]; then \
	    mv "$$install_path" "$$backup_path"; \
	    had_previous=1; \
	fi; \
	if ! mv "$$next_path" "$$install_path"; then \
	    if [ "$$had_previous" = 1 ]; then \
	        mv "$$backup_path" "$$install_path"; \
	        if [ "$(LAUNCH_AFTER_INSTALL)" = "1" ]; then open "$$install_path" >/dev/null 2>&1 || true; fi; \
	    fi; \
	    exit 1; \
	fi; \
	if ! ln -s "$$pair_path" "$$current_next"; then \
	    mv "$$install_path" "$$next_path"; \
	    if [ "$$had_previous" = 1 ]; then \
	        mv "$$backup_path" "$$install_path"; \
	        if [ "$(LAUNCH_AFTER_INSTALL)" = "1" ]; then open "$$install_path" >/dev/null 2>&1 || true; fi; \
	    fi; \
	    rm -rf "$$next_path"; \
	    exit 1; \
	fi; \
	if ! mv -fh "$$current_next" "$$current_path"; then \
	    mv "$$install_path" "$$next_path"; \
	    if [ "$$had_previous" = 1 ]; then \
	        mv "$$backup_path" "$$install_path"; \
	        if [ "$(LAUNCH_AFTER_INSTALL)" = "1" ]; then open "$$install_path" >/dev/null 2>&1 || true; fi; \
	    fi; \
	    rm -rf "$$next_path"; \
	    exit 1; \
	fi; \
	xattr -dr com.apple.quarantine "$$install_path" >/dev/null 2>&1 || true; \
	generated_hash="$$(sed -n '\''s/^public let gitHash = "\(.*\)"/\1/p'\'' Sources/Common/gitHashGenerated.swift)"; \
	if [ "$(LAUNCH_AFTER_INSTALL)" != "1" ]; then \
	    echo "Installed matching WinMux app and CLI on disk: $(VERSION) $$generated_hash"; \
	    echo "Launch and live client/server verification were deliberately skipped."; \
	    if [ "$$had_previous" = 1 ]; then echo "Rollback app preserved at $$backup_path"; fi; \
	    exit 0; \
	fi; \
	ready=0; \
	if launch_error="$$(open "$$install_path" 2>&1)"; then \
	    for attempt in $$(seq 1 100); do \
	        version_output="$$(/usr/bin/env -u WINMUX_APP_PATH "$$current_path/bin/winmux" --version 2>&1 || true)"; \
	        if printf "%s\n" "$$version_output" | grep -F "winmux CLI client version: $(VERSION) $$generated_hash" >/dev/null && \
	           printf "%s\n" "$$version_output" | grep -F "WinMux.app server version: $(VERSION) $$generated_hash" >/dev/null; then \
	            ready=1; \
	            break; \
	        fi; \
	        sleep 0.1; \
	    done; \
	else \
	    version_output="Failed to launch $$install_path: $$launch_error"; \
	fi; \
	if [ "$$ready" != 1 ]; then \
	    if [ "$(CODESIGN_IDENTITY)" = "-" ]; then \
	        echo "Installed the ad-hoc-signed WinMux app and CLI, but the pair has not passed its readiness check." >&2; \
	        echo "Accessibility approval is commonly required after an ad-hoc signature changes; a launch, config, or protocol failure can produce the same symptom." >&2; \
	        open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility" >/dev/null 2>&1 || true; \
	        echo "After WinMux is enabled and relaunched, run: make verify-installed" >&2; \
	        if [ "$$had_previous" = 1 ]; then echo "Rollback app preserved at $$backup_path" >&2; fi; \
	        exit 75; \
	    fi; \
	    echo "Installed WinMux failed the client/server version check; rolling back" >&2; \
	    osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	    for attempt in $$(seq 1 100); do \
	        if ! pgrep -x "$$app_name" >/dev/null 2>&1; then break; fi; \
	        sleep 0.1; \
	    done; \
	    if pgrep -x "$$app_name" >/dev/null 2>&1; then \
	        echo "Failed WinMux process did not quit; refusing to move a live app bundle during rollback" >&2; \
	        echo "New pair remains installed; rollback app remains at $$backup_path" >&2; \
	        exit 1; \
	    fi; \
	    failed_path="$$install_dir/.$$app_name.app.failed.$$(date +%Y%m%d%H%M%S).$$$$"; \
	    mv "$$install_path" "$$failed_path"; \
	    if [ "$$had_previous" = 1 ]; then mv "$$backup_path" "$$install_path"; fi; \
	    restore_link="$$local_install_root/.current-restore.$$$$"; \
	    if [ -n "$$old_current" ]; then \
	        ln -s "$$old_current" "$$restore_link"; \
	        mv -fh "$$restore_link" "$$current_path"; \
	    else \
	        rm -f "$$current_path"; \
	    fi; \
	    if [ "$$had_previous" = 1 ]; then open "$$install_path"; fi; \
	    echo "Failed build preserved at $$failed_path" >&2; \
	    exit 1; \
	fi; \
	echo "Installed matching WinMux app and CLI: $$version_output"; \
	if [ "$$had_previous" = 1 ]; then echo "Rollback app preserved at $$backup_path"; fi'

verify-installed:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	local_install_root="$$(cd "$(LOCAL_INSTALL_ROOT)" && pwd -P)"; \
	install_dir="$$(cd "$(APP_INSTALL_DIR)" && pwd -P)"; \
	current_path="$$local_install_root/current"; \
	install_path="$$install_dir/WinMux.app"; \
	test -L "$$current_path"; \
	test -x "$$current_path/bin/winmux"; \
	test -d "$$install_path"; \
	python3 -B script/verify-bundle-executables.py "$$install_path"; \
	/usr/bin/codesign --verify --deep --strict --verbose=2 "$$install_path"; \
	/usr/bin/codesign --verify --strict --verbose=2 "$$install_path/Contents/Helpers/winmux"; \
	cmp -s "$$current_path/bin/winmux" script/winmux-launcher.sh; \
	test "$$(cat "$$current_path/bin/winmux-app-path")" = "$$install_path"; \
	if ! version_output="$$(/usr/bin/env -u WINMUX_APP_PATH "$$current_path/bin/winmux" --version 2>&1)"; then \
	    printf "%s\n" "$$version_output" >&2; \
	    echo "Installed WinMux CLI could not negotiate with the running app" >&2; \
	    exit 1; \
	fi; \
	client_version="$$(printf "%s\n" "$$version_output" | /usr/bin/sed -n '\''s/^winmux CLI client version: //p'\'')"; \
	server_version="$$(printf "%s\n" "$$version_output" | /usr/bin/sed -n '\''s/^WinMux.app server version: //p'\'')"; \
	if [ -z "$$client_version" ] || [ "$$client_version" != "$$server_version" ]; then \
	    printf "%s\n" "$$version_output" >&2; \
	    echo "Installed WinMux app and CLI did not report the same build identity" >&2; \
	    exit 1; \
	fi; \
	printf "%s\n" "$$version_output"'

installed: install

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
