// Generated by script/chromium-tab-labels.py from Google Chrome 154.0.8037.58's locale.pak files; don't edit.

/// The text a Chromium browser puts before and after a tab's title in its accessible name.
struct ChromiumTabLabel: Sendable {
    let prefix: String
    let suffix: String
}

/// How a Chromium browser words a tab's memory use in its accessible name: the text before the
/// tab's title, between the title and the size, and after the size.
struct ChromiumTabMemoryLabel: Sendable {
    let prefix: String
    let marker: String
    let suffix: String
}

/// How each language labels a tab playing sound.
let chromiumTabPlayingLabels: [ChromiumTabLabel] = [
    .init(prefix: "", suffix: " – Oudio speel tans"), // af
    .init(prefix: "", suffix: " - ኦዲዮ በመጫወት ላይ ነው"), // am
    .init(prefix: "", suffix: " - تشغيل الصوت"), // ar
    .init(prefix: "", suffix: " – възпроизвежда се звук"), // bg
    .init(prefix: "", suffix: " - অডিও বাজছে"), // bn
    .init(prefix: "", suffix: ": s'està reproduint àudio"), // ca
    .init(prefix: "", suffix: " – přehrává se zvuk"), // cs
    .init(prefix: "", suffix: " – der afspilles lyd"), // da
    .init(prefix: "", suffix: " – Audiowiedergabe"), // de
    .init(prefix: "", suffix: " - Αναπαραγωγή ήχου"), // el
    .init(prefix: "", suffix: " - Audio playing"), // en
    .init(prefix: "", suffix: " – Audio playing"), // en_GB
    .init(prefix: "", suffix: ": reproducción de audio"), // es
    .init(prefix: "", suffix: ": Reproducción de audio"), // es_419
    .init(prefix: "", suffix: " – heli esitatakse"), // et
    .init(prefix: "", suffix: " - پخش خودکار"), // fa
    .init(prefix: "", suffix: " – toistaa ääntä"), // fi
    .init(prefix: "", suffix: " - May tumutugtog na audio"), // fil
    .init(prefix: "", suffix: "\u{a0}–\u{a0}Lecture audio"), // fr
    .init(prefix: "", suffix: " - ઑડિઓ ચલાવવું"), // gu
    .init(prefix: "", suffix: " - אודיו מופעל"), // he
    .init(prefix: "", suffix: " - ऑडियो चलाया जा रहा है"), // hi
    .init(prefix: "", suffix: " – reprodukcija zvuka"), // hr
    .init(prefix: "", suffix: " – Hanglejátszás"), // hu
    .init(prefix: "", suffix: " - Pemutaran audio"), // id
    .init(prefix: "", suffix: " - Riproduzione audio in corso"), // it
    .init(prefix: "", suffix: " - オーディオ再生中です"), // ja
    .init(prefix: "", suffix: " - ಆಡಿಯೋ ಪ್ಲೇ ಆಗುತ್ತಿದೆ"), // kn
    .init(prefix: "", suffix: " - 오디오 재생"), // ko
    .init(prefix: "„", suffix: "“ – garso įrašo paleidimas"), // lt
    .init(prefix: "", suffix: "\u{a0}— audio atskaņošana"), // lv
    .init(prefix: "", suffix: " - ഓഡിയോ പ്ലേ ചെയ്യുന്നു"), // ml
    .init(prefix: "", suffix: " - ऑडिओ प्ले करीत आहे"), // mr
    .init(prefix: "", suffix: " - Audio sedang dimainkan"), // ms
    .init(prefix: "", suffix: " – lyd spilles av"), // nb
    .init(prefix: "", suffix: ": audio wordt afgespeeld"), // nl
    .init(prefix: "", suffix: " – odtwarzanie dźwięku"), // pl
    .init(prefix: "", suffix: " - Reprodução de áudio"), // pt_BR
    .init(prefix: "", suffix: " – áudio em reprodução"), // pt_PT
    .init(prefix: "", suffix: " – se redă sunet"), // ro
    .init(prefix: "", suffix: ": воспроизводится аудио"), // ru
    .init(prefix: "", suffix: " – Prehráva sa zvuk"), // sk
    .init(prefix: "", suffix: " – zvok se predvaja"), // sl
    .init(prefix: "", suffix: " – Пушта се аудио садржај"), // sr
    .init(prefix: "", suffix: " – spelar upp ljud"), // sv
    .init(prefix: "", suffix: " - Kucheza sauti"), // sw
    .init(prefix: "", suffix: " - ஆடியோ இயக்கப்படுகிறது"), // ta
    .init(prefix: "", suffix: " - ఆడియో ప్లే చేస్తోంది"), // te
    .init(prefix: "", suffix: " - เล่นอัตโนมัติ"), // th
    .init(prefix: "", suffix: " - Ses çalıyor"), // tr
    .init(prefix: "", suffix: " – відтворюється аудіо"), // uk
    .init(prefix: "", suffix: " - آڈیو چلا رہی ہے"), // ur
    .init(prefix: "", suffix: " - Phát âm thanh"), // vi
    .init(prefix: "", suffix: " - 正在播放音频"), // zh_CN
    .init(prefix: "", suffix: " - 音訊播放中"), // zh_TW
]

/// How each language labels a muted tab that was just playing sound.
let chromiumTabMutedLabels: [ChromiumTabLabel] = [
    .init(prefix: "", suffix: " – Oudio is gedemp"), // af
    .init(prefix: "", suffix: " - ኦዲዮ ድምፀ-ከል ተደርጎበታል"), // am
    .init(prefix: "", suffix: " - تم كتم الصوت"), // ar
    .init(prefix: "", suffix: " – звукът е заглушен"), // bg
    .init(prefix: "", suffix: " - অডিও মিউট রয়েছে"), // bn
    .init(prefix: "", suffix: ": l'àudio està desactivat"), // ca
    .init(prefix: "", suffix: " – zvuk je vypnutý"), // cs
    .init(prefix: "", suffix: " – lyden er slået fra"), // da
    .init(prefix: "", suffix: " – stummgeschaltet"), // de
    .init(prefix: "", suffix: " - Ο ήχος τέθηκε σε σίγαση"), // el
    .init(prefix: "", suffix: " - Audio muted"), // en
    .init(prefix: "", suffix: " – Audio muted"), // en_GB
    .init(prefix: "", suffix: ": audio silenciado"), // es
    .init(prefix: "", suffix: ": Audio silenciado"), // es_419
    .init(prefix: "", suffix: " – heli on vaigistatud"), // et
    .init(prefix: "", suffix: " - بی\u{200c}صدا شده است"), // fa
    .init(prefix: "", suffix: " – ääni mykistetty"), // fi
    .init(prefix: "", suffix: " - Naka-mute ang audio"), // fil
    .init(prefix: "", suffix: "\u{a0}–\u{a0}Son coupé"), // fr
    .init(prefix: "", suffix: " - ઑડિઓ મ્યૂટ કર્યો"), // gu
    .init(prefix: "", suffix: " - האודיו הושתק"), // he
    .init(prefix: "", suffix: " - ऑडियो म्यूट किया गया"), // hi
    .init(prefix: "", suffix: " – zvuk je isključen"), // hr
    .init(prefix: "", suffix: " – Hang kikapcsolva"), // hu
    .init(prefix: "", suffix: " - Audio dibisukan"), // id
    .init(prefix: "", suffix: " - Audio disattivato"), // it
    .init(prefix: "", suffix: " - オーディオがミュートされています"), // ja
    .init(prefix: "", suffix: " - ಆಡಿಯೋ ಮ್ಯೂಟ್ ಮಾಡಲಾಗಿದೆ"), // kn
    .init(prefix: "", suffix: " - 오디오 음소거"), // ko
    .init(prefix: "„", suffix: "“ – garso įrašas nutildytas"), // lt
    .init(prefix: "", suffix: "\u{a0}— izslēgta skaņa"), // lv
    .init(prefix: "", suffix: " - ഓഡിയോ മ്യൂട്ടുചെയ്\u{200c}തു"), // ml
    .init(prefix: "", suffix: " - ऑडिओ म्यूट केला"), // mr
    .init(prefix: "", suffix: " - Audio diredam"), // ms
    .init(prefix: "", suffix: " – lyden er kuttet"), // nb
    .init(prefix: "", suffix: ": audio uitgezet"), // nl
    .init(prefix: "", suffix: " – dźwięk wyciszony"), // pl
    .init(prefix: "", suffix: " - Áudio desativado"), // pt_BR
    .init(prefix: "", suffix: " – áudio desativado"), // pt_PT
    .init(prefix: "", suffix: " – sunetul a fost dezactivat"), // ro
    .init(prefix: "", suffix: ": звук отключен"), // ru
    .init(prefix: "", suffix: " – Vypnuté zvuky"), // sk
    .init(prefix: "", suffix: " – zvok utišan"), // sl
    .init(prefix: "", suffix: " – Звук је искључен"), // sr
    .init(prefix: "", suffix: " – ljud av"), // sv
    .init(prefix: "", suffix: " - Sauti imezimwa"), // sw
    .init(prefix: "", suffix: " - ஆடியோ முடக்கப்பட்டது"), // ta
    .init(prefix: "", suffix: " - ఆడియో మ్యూట్ చేయబడింది"), // te
    .init(prefix: "", suffix: " - ปิดเสียงอยู่"), // th
    .init(prefix: "", suffix: " - Ses kapatıldı"), // tr
    .init(prefix: "", suffix: " – звук вимкнено"), // uk
    .init(prefix: "", suffix: " - آڈیو خاموش ہے"), // ur
    .init(prefix: "", suffix: " - Đã tắt âm thanh"), // vi
    .init(prefix: "", suffix: " - 音频已静音"), // zh_CN
    .init(prefix: "", suffix: " - 靜音"), // zh_TW
]

/// How each language labels a tab's memory use, and its high memory use.
let chromiumTabMemoryLabels: [ChromiumTabMemoryLabel] = [
    .init(prefix: "", marker: " – geheuegebruik – ", suffix: ""), // af
    .init(prefix: "", marker: " – hoë geheuegebruik – ", suffix: ""), // af
    .init(prefix: "", marker: " - የማህደረ ትውስታ አጠቃቀም - ", suffix: ""), // am
    .init(prefix: "", marker: " - ከፍተኛ የማህደረ ትውስታ አጠቃቀም - ", suffix: ""), // am
    .init(prefix: "\"", marker: "\" - استخدام الذاكرة - ", suffix: ""), // ar
    .init(prefix: "\"", marker: "\" - استخدام مرتفع للذاكرة - ", suffix: ""), // ar
    .init(prefix: "", marker: "\u{a0}– използвана памет: ", suffix: ""), // bg
    .init(prefix: "", marker: "\u{a0}– голямо количество използвана памет: ", suffix: ""), // bg
    .init(prefix: "", marker: " - মেমরির ব্যবহার - ", suffix: ""), // bn
    .init(prefix: "", marker: " - বেশি মেমরির ব্যবহার - ", suffix: ""), // bn
    .init(prefix: "", marker: " - Ús de memòria - ", suffix: ""), // ca
    .init(prefix: "", marker: " - Ús elevat de memòria - ", suffix: ""), // ca
    .init(prefix: "", marker: "\u{a0}– Využití paměti\u{a0}– ", suffix: ""), // cs
    .init(prefix: "", marker: "\u{a0}– Vysoké využití paměti\u{a0}– ", suffix: ""), // cs
    .init(prefix: "", marker: " – Hukommelsesforbrug – ", suffix: ""), // da
    .init(prefix: "", marker: " – Højt hukommelsesforbrug –", suffix: ""), // da
    .init(prefix: "", marker: "\u{a0}– Arbeitsspeichernutzung\u{a0}– ", suffix: ""), // de
    .init(prefix: "", marker: "\u{a0}– Hohe Arbeitsspeichernutzung\u{a0}– ", suffix: ""), // de
    .init(prefix: "", marker: " - Χρήση μνήμης - ", suffix: ""), // el
    .init(prefix: "", marker: " - Υψηλή χρήση μνήμης - ", suffix: ""), // el
    .init(prefix: "", marker: " - Memory usage - ", suffix: ""), // en, en_GB
    .init(prefix: "", marker: " - High memory usage - ", suffix: ""), // en, en_GB
    .init(prefix: "Uso de memoria de ", marker: ": ", suffix: ""), // es
    .init(prefix: "Uso de memoria elevado de ", marker: ": ", suffix: ""), // es
    .init(prefix: "", marker: ": Uso de memoria: ", suffix: ""), // es_419
    .init(prefix: "", marker: ": Uso elevado de memoria: ", suffix: ""), // es_419
    .init(prefix: "", marker: " - Mälukasutus - ", suffix: ""), // et
    .init(prefix: "", marker: " - Suur mälukasutus - ", suffix: ""), // et
    .init(prefix: "", marker: " - استفاده از حافظه - ", suffix: ""), // fa
    .init(prefix: "", marker: " - استفاده زیاد از حافظه - ", suffix: ""), // fa
    .init(prefix: "", marker: " - Muistin käyttö - ", suffix: ""), // fi
    .init(prefix: "", marker: " - Korkea muistin käyttö - ", suffix: ""), // fi
    .init(prefix: "", marker: " - Paggamit ng memory - ", suffix: ""), // fil
    .init(prefix: "", marker: " - Mataas na paggamit ng memory - ", suffix: ""), // fil
    .init(prefix: "", marker: " - Utilisation de la mémoire - ", suffix: ""), // fr
    .init(prefix: "", marker: " - Utilisation élevée de la mémoire - ", suffix: ""), // fr
    .init(prefix: "", marker: " - મેમેરીનો વપરાશ - ", suffix: ""), // gu
    .init(prefix: "", marker: " - મેમરીનો ઉચ્ચ વપરાશ - ", suffix: ""), // gu
    .init(prefix: "", marker: " – השימוש בזיכרון – ", suffix: ""), // he
    .init(prefix: "", marker: " – שימוש בנפח גדול מהזיכרון – ", suffix: ""), // he
    .init(prefix: "", marker: " - मेमोरी का इस्तेमाल - ", suffix: ""), // hi
    .init(prefix: "", marker: " - मेमोरी का ज़्यादा इस्तेमाल - ", suffix: ""), // hi
    .init(prefix: "", marker: " – Upotreba memorije – ", suffix: ""), // hr
    .init(prefix: "", marker: " – Visoka upotreba memorije – ", suffix: ""), // hr
    .init(prefix: "", marker: " – Memóriahasználat – ", suffix: ""), // hu
    .init(prefix: "", marker: " – Nagy memóriahasználat – ", suffix: ""), // hu
    .init(prefix: "", marker: " - Penggunaan memori - ", suffix: ""), // id, ms
    .init(prefix: "", marker: " - Penggunaan memori tinggi - ", suffix: ""), // id, ms
    .init(prefix: "", marker: " - Memoria utilizzata - ", suffix: ""), // it
    .init(prefix: "", marker: " - Memoria utilizzata elevata - ", suffix: ""), // it
    .init(prefix: "", marker: " - メモリ使用量 - ", suffix: ""), // ja
    .init(prefix: "", marker: " - メモリを大量に使用 - ", suffix: ""), // ja
    .init(prefix: "", marker: " - ಮೆಮೊರಿ ಬಳಕೆ - ", suffix: ""), // kn
    .init(prefix: "", marker: " - ಹೆಚ್ಚಿನ ಮೆಮೊರಿ ಬಳಕೆ - ", suffix: ""), // kn
    .init(prefix: "", marker: " - 메모리 사용량 - ", suffix: ""), // ko
    .init(prefix: "", marker: " - 메모리 사용량 많음 - ", suffix: ""), // ko
    .init(prefix: "„", marker: "“ – atminties sąnaudos – ", suffix: ""), // lt
    .init(prefix: "„", marker: "“ – didelės atminties sąnaudos – ", suffix: ""), // lt
    .init(prefix: "", marker: "\u{a0}— atmiņas lietojums: ", suffix: ""), // lv
    .init(prefix: "", marker: "\u{a0}— liels atmiņas lietojums: ", suffix: ""), // lv
    .init(prefix: "", marker: " - മെമ്മറി ഉപയോഗം - ", suffix: ""), // ml
    .init(prefix: "", marker: " - ഉയർന്ന മെമ്മറി ഉപയോഗം - ", suffix: ""), // ml
    .init(prefix: "", marker: " - मेमरी वापर - ", suffix: ""), // mr
    .init(prefix: "", marker: " - उच्च मेमरी वापर - ", suffix: ""), // mr
    .init(prefix: "", marker: " – minnebruk – ", suffix: ""), // nb
    .init(prefix: "", marker: " – høy minnebruk – ", suffix: ""), // nb
    .init(prefix: "", marker: " - Geheugengebruik - ", suffix: ""), // nl
    .init(prefix: "", marker: " - Intensief geheugengebruik - ", suffix: ""), // nl
    .init(prefix: "", marker: "\u{a0}– wykorzystanie pamięci\u{a0}– ", suffix: ""), // pl
    .init(prefix: "", marker: "\u{a0}– duże wykorzystanie pamięci\u{a0}– ", suffix: ""), // pl
    .init(prefix: "Uso da memória em ", marker: ": ", suffix: ""), // pt_BR
    .init(prefix: "Uso elevado da memória em ", marker: ": ", suffix: ""), // pt_BR
    .init(prefix: "", marker: " – Utilização de memória – ", suffix: ""), // pt_PT
    .init(prefix: "", marker: " – Utilização elevada de memória – ", suffix: ""), // pt_PT
    .init(prefix: "", marker: " – Utilizarea memoriei – ", suffix: ""), // ro
    .init(prefix: "", marker: " – Utilizare intensă a memoriei – ", suffix: ""), // ro
    .init(prefix: "Вкладка \"", marker: "\" использует ", suffix: " памяти"), // ru
    .init(prefix: "Вкладка \"", marker: "\" использует много памяти: ", suffix: ""), // ru
    .init(prefix: "", marker: " – Využitie pamäte – ", suffix: ""), // sk
    .init(prefix: "", marker: " – Vysoké využitie pamäte – ", suffix: ""), // sk
    .init(prefix: "", marker: " – Uporaba pomnilnika – ", suffix: ""), // sl
    .init(prefix: "", marker: " – Visoka uporaba pomnilnika – ", suffix: ""), // sl
    .init(prefix: "", marker: " – Потрошња меморије – ", suffix: ""), // sr
    .init(prefix: "", marker: " – Висока потрошња меморије – ", suffix: ""), // sr
    .init(prefix: "", marker: " – Minnesanvändning – ", suffix: ""), // sv
    .init(prefix: "", marker: " – Hög minnesanvändning – ", suffix: ""), // sv
    .init(prefix: "", marker: " - Matumizi ya hifadhi - ", suffix: ""), // sw
    .init(prefix: "", marker: " - Matumizi ya juu ya hifadhi - ", suffix: ""), // sw
    .init(prefix: "", marker: " - நினைவக உபயோகம் - ", suffix: ""), // ta
    .init(prefix: "", marker: " - அதிகமான நினைவக உபயோகம் - ", suffix: ""), // ta
    .init(prefix: "", marker: " - మెమరీ వినియోగం - ", suffix: ""), // te
    .init(prefix: "", marker: " - అధిక మెమరీని వినియోగించింది - ", suffix: ""), // te
    .init(prefix: "", marker: " - การใช้งานหน่วยความจำ - ", suffix: ""), // th
    .init(prefix: "", marker: " - การใช้งานหน่วยความจำสูง - ", suffix: ""), // th
    .init(prefix: "", marker: " - Bellek kullanımı - ", suffix: ""), // tr
    .init(prefix: "", marker: " - Yüksek bellek kullanımı - ", suffix: ""), // tr
    .init(prefix: "", marker: " – використання пам’яті – ", suffix: ""), // uk
    .init(prefix: "", marker: " – надмірне використання пам’яті – ", suffix: ""), // uk
    .init(prefix: "", marker: " - میموری کا استعمال - ", suffix: ""), // ur
    .init(prefix: "", marker: " - زیادہ میموری کا استعمال - ", suffix: ""), // ur
    .init(prefix: "", marker: " – Mức sử dụng bộ nhớ – ", suffix: ""), // vi
    .init(prefix: "", marker: " – Mức sử dụng bộ nhớ cao – ", suffix: ""), // vi
    .init(prefix: "", marker: " - 内存用量 - ", suffix: ""), // zh_CN
    .init(prefix: "", marker: " - 内存用量高 - ", suffix: ""), // zh_CN
    .init(prefix: "", marker: " - 記憶體用量 - ", suffix: ""), // zh_TW
    .init(prefix: "", marker: " - 高記憶體用量 - ", suffix: ""), // zh_TW
]
