#!/usr/bin/env python3
"""Writes the Chromium tab-label table that Tabs mode reads sound from.

Chromium browsers add a tab's sound to its accessible name ("Title - Audio playing"), in the
browser's language. This reads those formats from an installed browser's locale.pak files, in
every language it ships, and prints Sources/AppBundle/browser/ChromiumTabLabels.swift.

    python3 -B script/chromium-tab-labels.py > Sources/AppBundle/browser/ChromiumTabLabels.swift
"""

import argparse
import pathlib
import struct
import sys

DEFAULT_BROWSER = "/Applications/Google Chrome.app"
# The English formats, found by text because resource ids change between releases.
PLAYING = "$1 - Audio playing"
MUTED = "$1 - Audio muted"
MEMORY = ["$1 - Memory usage - $2", "$1 - High memory usage - $2"]


def read_pak(path):
    data = path.read_bytes()
    (version,) = struct.unpack_from("<I", data, 0)
    if version != 5:
        raise SystemExit(f"{path}: unsupported pak version {version}")
    encoding = data[4]
    count, aliases = struct.unpack_from("<HH", data, 8)
    entries = [struct.unpack_from("<HI", data, 12 + index * 6) for index in range(count + 1)]
    strings = {}
    for index in range(count):
        resource, offset = entries[index]
        raw = data[offset:entries[index + 1][1]]
        strings[resource] = raw.decode("utf-8" if encoding == 1 else "utf-16-le", errors="replace")
    base = 12 + (count + 1) * 6
    for index in range(aliases):
        resource, target = struct.unpack_from("<HH", data, base + index * 4)
        strings[resource] = strings[entries[target][0]]
    return strings


def resources(browser):
    frameworks = pathlib.Path(browser, "Contents", "Frameworks")
    matches = sorted(frameworks.glob("*.framework/Versions/Current/Resources"))
    if not matches:
        raise SystemExit(f"No framework resources under {frameworks}")
    return matches[0]


def swift_string(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + "".join(ch if 0x20 <= ord(ch) < 0x7F or ord(ch) > 0xA0 and ch not in "\u200c\u200d\u200e\u200f"
                         else f"\\u{{{ord(ch):x}}}" for ch in escaped) + '"'


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--browser", default=DEFAULT_BROWSER, help="the Chromium browser app to read")
    arguments = parser.parse_args()
    root = resources(arguments.browser)
    locales = sorted(path.stem for path in root.glob("*.lproj")
                     if not path.stem.endswith(("_FEMININE", "_MASCULINE", "_NEUTER")))
    english = read_pak(root / "en.lproj" / "locale.pak")

    def resource(text):
        found = [key for key, value in english.items() if value == text]
        if len(found) != 1:
            raise SystemExit(f"Expected one English {text!r}, found {len(found)}")
        return found[0]

    playing, muted = resource(PLAYING), resource(MUTED)
    memory = [resource(text) for text in MEMORY]
    affixes = {"playing": {}, "muted": {}, "memory": {}}
    for locale in locales:
        strings = read_pak(root / f"{locale}.lproj" / "locale.pak")
        for kind, key in (("playing", playing), ("muted", muted)):
            text = strings.get(key, "")
            if text.count("$1") != 1:
                continue
            prefix, suffix = text.split("$1")
            if suffix:
                affixes[kind].setdefault((prefix, suffix), []).append(locale)
        for key in memory:
            text = strings.get(key, "")
            # "<prefix><title><marker><size><suffix>", as every language words it.
            if text.count("$1") == 1 and text.count("$2") == 1 and text.index("$1") < text.index("$2"):
                prefix, rest = text.split("$1")
                marker, suffix = rest.split("$2")
                if marker:
                    affixes["memory"].setdefault((prefix, marker, suffix), []).append(locale)

    version = (pathlib.Path(arguments.browser, "Contents", "Info.plist").read_bytes().split(b"<key>CFBundleShortVersionString</key>")[1]
               .split(b"<string>")[1].split(b"</string>")[0].decode())
    name = pathlib.Path(arguments.browser).stem
    out = sys.stdout
    out.write(f"// Generated by script/chromium-tab-labels.py from {name} {version}'s locale.pak files; don't edit.\n\n")
    out.write("/// The text a Chromium browser puts before and after a tab's title in its accessible name.\n")
    out.write("struct ChromiumTabLabel: Sendable {\n    let prefix: String\n    let suffix: String\n}\n\n")
    out.write("/// How a Chromium browser words a tab's memory use in its accessible name: the text before the\n")
    out.write("/// tab's title, between the title and the size, and after the size.\n")
    out.write("struct ChromiumTabMemoryLabel: Sendable {\n    let prefix: String\n    let marker: String\n    let suffix: String\n}\n\n")
    for kind, name, summary in (("playing", "chromiumTabPlayingLabels", "a tab playing sound"),
                                ("muted", "chromiumTabMutedLabels", "a muted tab that was just playing sound")):
        out.write(f"/// How each language labels {summary}.\n")
        out.write(f"let {name}: [ChromiumTabLabel] = [\n")
        for (prefix, suffix), where in affixes[kind].items():
            out.write(f"    .init(prefix: {swift_string(prefix)}, suffix: {swift_string(suffix)}), // {', '.join(where)}\n")
        out.write("]\n\n")
    out.write("/// How each language labels a tab's memory use, and its high memory use.\n")
    out.write("let chromiumTabMemoryLabels: [ChromiumTabMemoryLabel] = [\n")
    for (prefix, marker, suffix), where in affixes["memory"].items():
        out.write(f"    .init(prefix: {swift_string(prefix)}, marker: {swift_string(marker)}, suffix: {swift_string(suffix)}), "
                  f"// {', '.join(where)}\n")
    out.write("]\n")


if __name__ == "__main__":
    main()
