#!/usr/bin/env python3
"""Build a signed preview locally; hosted CI stays available until publication succeeds."""

import importlib.util
import json
import os
from pathlib import Path
import re
import subprocess
import sys

spec = importlib.util.spec_from_file_location("preview", Path(__file__).with_name("ci-prerelease.py"))
preview = importlib.util.module_from_spec(spec)
spec.loader.exec_module(preview)
GENERATED = (Path("Sources/Common/gitHashGenerated.swift"), Path("Sources/Common/versionGenerated.swift"))


def run(*args, **kwargs):
    subprocess.run(args, check=True, **kwargs)


def verify_source(commit, expected_generated):
    if preview.release.run("git", "rev-parse", "HEAD") != commit:
        raise ValueError("HEAD changed during the build; refusing publication.")
    changed = set(preview.release.run("git", "diff", "--name-only", "HEAD").splitlines())
    if changed - {str(path) for path in GENERATED}:
        raise ValueError("Source changed during the build; refusing publication.")
    if preview.release.run("git", "ls-files", "--others", "--exclude-standard"):
        raise ValueError("Untracked source appeared during the build; refusing publication.")
    for path, expected in expected_generated.items():
        if path.read_bytes() != expected:
            raise ValueError(f"Build metadata changed during the build: {path}")


def cancel_redundant_ci(commit):
    runs = json.loads(preview.release.run("gh", "run", "list", "--repo", preview.REPOSITORY,
                                         "--commit", commit, "--limit", "100",
                                         "--json", "databaseId,workflowName,status"))
    for job in runs:
        if job["workflowName"] == "Publish automatic prerelease" and job["status"] != "completed":
            result = subprocess.run(["gh", "run", "cancel", str(job["databaseId"]), "--repo", preview.REPOSITORY])
            if result.returncode:
                print("The release is published; its hosted job may already have finished.")


def main():
    if sys.argv[1:] == ["--help"]:
        print("Run make prerelease-local with your Developer ID, team, notarization profile, and pinned Swift toolchain configured.")
        return
    if sys.argv[1:]:
        raise ValueError("Usage: local-prerelease.py [--help]")
    commit = preview.check_context(local=True)
    if preview.release.run("git", "status", "--porcelain"):
        raise ValueError("Commit or stash source changes before publishing a local prerelease.")
    origin = preview.release.run("git", "remote", "get-url", "origin")
    if origin not in (f"https://github.com/{preview.REPOSITORY}.git", f"git@github.com:{preview.REPOSITORY}.git"):
        raise ValueError("Origin must identify alanzchen/winmux before pushing a local preview.")
    lock = Path(".local/prerelease.lock")
    lock.parent.mkdir(exist_ok=True)
    try:
        lock.mkdir()
    except FileExistsError as error:
        raise ValueError("Another local prerelease build holds .local/prerelease.lock.") from error
    original = {path: path.read_bytes() for path in GENERATED}
    expected = {}
    try:
        branch = preview.release.run("git", "branch", "--show-current")
        run("git", "push", "origin", f"HEAD:refs/heads/{branch}")
        if not os.environ.get("DEVELOPMENT_TEAM") or os.environ.get("CODESIGN_IDENTITY") == "-":
            raise ValueError("Set DEVELOPMENT_TEAM and a Developer ID Application CODESIGN_IDENTITY; hosted CI remains available.")
        pinned = Path(".swift-version").read_text().strip()
        for args in (["/bin/bash", "-c", "source script/setup.sh; swift --version"], ["xcrun", "swift", "--version"]):
            output = subprocess.check_output(args, text=True)
            if not re.search(rf"Swift version {re.escape(pinned)}(?:\s|$)", output):
                raise ValueError(f"Configure Swift and Xcode's TOOLCHAINS to use pinned Swift {pinned}; hosted CI remains available.")
        tag, already_published = preview.prepare(local=True)
        if not already_published:
            version = tag[1:]
            short_hash = preview.release.run("git", "rev-parse", "--short", "HEAD")
            expected = {
                GENERATED[0]: f'// FILE IS GENERATED BY Makefile\npublic let gitHash = "{commit}"\npublic let gitShortHash = "{short_hash}"\n'.encode(),
                GENERATED[1]: f'// FILE IS GENERATED BY Makefile\npublic let winMuxAppVersion = "{version}"\n'.encode(),
            }
            directory = Path(".local/prereleases") / tag
            directory.mkdir(parents=True, exist_ok=True)
            environment = dict(os.environ, VERSION=version, RELEASE_TAG=tag, RELEASE_DIR=str(directory.resolve()),
                               UPDATE_FEED_URL=f"https://raw.githubusercontent.com/{preview.REPOSITORY}/updates/prerelease.xml")
            run("/bin/bash", "-c", "source script/setup.sh; swift test; swift build", env=environment)
            run("python3", "-B", "-m", "unittest", "discover", "-s", "script", "-p", "test_*.py")
            run("make", "release", f"VERSION={version}", f"RELEASE_TAG={tag}",
                f"RELEASE_DIR={directory.resolve()}", f"CLI_STAGE_PATH={directory.resolve() / 'winmux'}",
                "NOTARIZE=1", "GENERATE_APPCAST=1", "PUBLISH=0", env=environment)
            verify_source(commit, expected)
            os.environ.update(VERSION=version, RELEASE_TAG=tag, RELEASE_DIR=str(directory.resolve()))
            tag = preview.publish(local=True)
        # Only successful publication/feed promotion can suppress the hosted fallback.
        try:
            cancel_redundant_ci(commit)
        except subprocess.CalledProcessError:
            print("Release is published; could not cancel the redundant CI job.")
        print(f"Local preview ready: https://github.com/{preview.REPOSITORY}/releases/tag/{tag}")
    finally:
        for path, generated in expected.items():
            if path.exists() and path.read_bytes() == generated:
                path.write_bytes(original[path])
        lock.rmdir()


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        sys.exit(str(error))
